New Lab to show how to use the AWS CLI to interact with the WellArchitected Tool
awslabs/aws-well-architected-labs pull request #188
Opened 2020-12-18 18:31 UTC by ericpullen

New lab in wellarchitected for how to use the API. I also created a new shortcode for installing the latest version of the AWSCLI v2.

2020-12-23 04:00 UTC, setheliot requested changes
I liked it!

Hopefully my comments are helpful - most are optional.

2021-01-04 19:42 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/_index.md
> ++++
Does look odd, but I'm going to leave it at this point.

2021-01-04 19:51 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/2_create_workload.md
> +      * **lenses** - The list of lenses associated with the workload. All workloads must include the "wellarchitected" lens as a base, but can include additional lenses. For this lab, we are also inc
Yea, the oddity is that you can't just create a workload without the --lenses parameter at all (it errors out). So, just to show the user that you can specify both the wellarchitected base framework and a lens at the same time, I wrote it this way.

2021-01-04 19:54 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/2_create_workload.md
> +    ![AddRemoveLens1](/watool/200_Using_AWSCLI_To_Manage_WA_Reviews/Images/2/AddRemoveLens1.png)
Just showing them what they should expect the output to be for these commands. I've always erred on the side of more screenshots than less. I'll see what kind of feedback we get (if any) and possibly streamline this more later.

2021-01-04 20:14 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/3_perform_review.md
> +1. Now we need to get the rest of the ChoiceID's for each of the best practices we want to select for the question
I'm going to leave it as-is for now since I like the idea that they need to search for the specific Choice via the text (which I would assume you would want to be specific if you were writing integrations with external systems without human interaction).

2021-01-04 20:24 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/4_save_milestone.md
> +1. The return value will be the workloadId and the Milestone number assigned.
🤷

2021-01-04 20:25 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/4_save_milestone.md
> +    aws wellarchitected get-milestone --workload-id "<WorkloadId>" --milestone-number 1
For the purposes of the lab, we created a new workload and we just had them create a milestone, so it would alway be 1.

2021-01-04 20:28 UTC, ericpullen commented on content/Well-ArchitectedTool/200_Labs/200_Using_AWSCLI_To_Manage_WA_Reviews/5_view_report.md
> +1. Using the [get-lens-review-report](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wellarchitected/get-lens-review-report.html), you can retrieve the pillar review report in PDF
Lots of trial and error :)

2021-01-04 21:29 UTC, ericpullen reviewed
I believe all changes have been incorporated.

2021-01-04 21:46 UTC, merged