Updated REL lab - deploy and update cloudformation - added section fo…
awslabs/aws-well-architected-labs pull request #241
Opened 2021-03-19 21:19 UTC by TheFuz

…r multi-region deployments with StackSets

*Issue #, if available:* N/A

*Description of changes:* Added a new section on multi-region deployments with CloudFormation StackSets for the REL lab - 200 Deploy and Update CloudFormation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-22 21:56 UTC, setheliot requested changes
looks good. I have some small suggestions

Also, I have not actually executed the lab.  This is just a read-review

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/4_add_s3.md
> +    * Be cautious to maintin the two-space indents where indicated
thanks for fixing my one typo... can you also fix my other while you are in there?  "maintin"

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
>      * **Tags:** Use this YAML block:
I think these should say "Refers to" with an "s" after "refer" 

Also note, you missed line 51

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * When referencing **SecurityGroupIds**, CloudFormation is expecting a _list_ of security groups. You therefore need to list the security group like this:
not sure you needed to change "referring to", but ok
For line 62 how about "the CloudFormation template is"

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * Delete the following properties from the EC2 resource
Thanks again for catching all these typos :-)

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * The [!GetAtt function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html) can return various attributes of the resource. In this case the p
the link is good.  Can you please add the back-ticks back?

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +AWS CloudFormation StackSets requires specific permissions to be able to deploy stacks in multiple AWS accounts across multiple AWS Regions. It needs an administrator role that is used to perform Sta
"in the account where you are creating the StackSet (The Administrator account - see the diagram above)

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +For this lab, I will walk you through the process of creating a StackSet to deploy stacks across multiple regions in a single account (the same account where the StackSet is being created). For simpl
do not use "I" -- use "we" for AWS (or the lab author) and "you" for the customer

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the administrator role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetAdministrationRole.yml
I know you prefer to put stack sin S3, but please do not mix-and-match.  Please check in the CloudFormation template as part of this PR and reference it from github, like the other templates used in this lab

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the administrator role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetAdministrationRole.yml
see 

>To download a sample solution, right-click and download this link: simple_stack_plus_s3_ec2.yaml

in the previous step for an example

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +Now that a StackSet administrator role has been created, we need to create the StackSet execution role.
please put both roles into one template.

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the execution role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetExecutionRole.yml
please use `.yaml` for consistency

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the administrator role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetAdministrationRole.yml
please use `.yaml` for consistency

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +    * Click Choose file and supply the CloudFormation template you downloaded: _AWSCloudFormationStackSetAdministrationRole.yml_
please use `.yaml` for consistency

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the sample template [simple_stackset_plus_s3_ec2_server.yaml](/Reliability/200_Deploy_and_Update_CloudFormation/Code/CloudFormation/simple_stackset_plus_s3_ec2_server.yaml)
Add mention that this should be the same as the currently deployed stack assuming you have done all previous steps

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +    ![StackSetRegions](/Reliability/200_Deploy_and_Update_CloudFormation/Images/StackSetRegions.png?classes=lab_picture_auto)
This screenshot has weird wrapping on the "Remove" buttons

2021-03-22 21:56 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Under **Specify regions** select 2 regions you would like to deploy the stacks across. I have selected **US East (N.Virginia)** and **US West (Oregon)**.
Do these have to be two regions **different** than the region already used for the lab?  If they use the same region they used for the lab (and already have this stack) will it succeed or will there be conflicts?

2021-03-29 15:38 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
>      * **Tags:** Use this YAML block:
I changed it to "References" to align with CFN terminology. The logical link between "data" within a template is a reference.

2021-03-29 15:38 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * When referencing **SecurityGroupIds**, CloudFormation is expecting a _list_ of security groups. You therefore need to list the security group like this:
I changed it to "References" to align with CFN terminology. The logical link between "data" within a template is a reference.

2021-03-29 15:38 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * Delete the following properties from the EC2 resource
:)

2021-03-29 15:53 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * The [!GetAtt function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html) can return various attributes of the resource. In this case the p
I removed it since this is not something that they need to copy. My understanding is that back-ticks are only for text that needs to be copied. Should I highlight by making it bold instead?

2021-03-29 15:55 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the execution role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetExecutionRole.yml
These are templates provided in our public documentation so I cannot change the extension.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-prereqs-self-managed.html

2021-03-29 15:55 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +    * Click Choose file and supply the CloudFormation template you downloaded: _AWSCloudFormationStackSetAdministrationRole.yml_
These are templates provided in our public documentation so I cannot change the extension.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-prereqs-self-managed.html

2021-03-29 15:56 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the sample template [simple_stackset_plus_s3_ec2_server.yaml](/Reliability/200_Deploy_and_Update_CloudFormation/Code/CloudFormation/simple_stackset_plus_s3_ec2_server.yaml)
This is a different template, not the same as the previous one.

2021-03-29 15:56 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +    ![StackSetRegions](/Reliability/200_Deploy_and_Update_CloudFormation/Images/StackSetRegions.png?classes=lab_picture_auto)
Yeah its one of those weird console things, I'll check to see if I can make it go away.

2021-03-29 16:27 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Under **Specify regions** select 2 regions you would like to deploy the stacks across. I have selected **US East (N.Virginia)** and **US West (Oregon)**.
No conflicts. Updated the guide to make this clear.

2021-03-29 17:27 UTC, setheliot requested changes

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +    * The [!GetAtt function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html) can return various attributes of the resource. In this case the p
I use back ticks for anything that is code (not the English language... keywords and such) - bold is fine too

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +For this lab, I will walk you through the process of creating a StackSet to deploy stacks across multiple regions in a single account (the same account where the StackSet is being created). For simpl
???

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the administrator role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetAdministrationRole.yml
ok, I did not realize these were AWS-wide templates... no problem then

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +    * Click Choose file and supply the CloudFormation template you downloaded: _AWSCloudFormationStackSetAdministrationRole.yml_
oh, ok then :-)

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the execution role CloudFormation template - https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetExecutionRole.yml
yup, got it... sorry

2021-03-29 17:27 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +1.  Download the sample template [simple_stackset_plus_s3_ec2_server.yaml](/Reliability/200_Deploy_and_Update_CloudFormation/Code/CloudFormation/simple_stackset_plus_s3_ec2_server.yaml)
ah ok... then mention what is the difference between this (simple_stackset_plus_s3_ec2_server.yaml) and the currently deployed stack.  What does this template actually do?  Explain why do we need this template instead of using simple_stack_plus_s3_ec2_server.yaml

2021-03-30 03:38 UTC, TheFuz commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/6_multi_region_deploy.md
> +Now that a StackSet administrator role has been created, we need to create the StackSet execution role.
Templates are provided by AWS. You have acknowledged this in another comment, but I'm calling it out here as well to leave a good audit trail :)

2021-03-31 22:56 UTC, setheliot approved these changes

2021-03-31 23:01 UTC, setheliot requested changes

2021-03-31 23:01 UTC, setheliot commented on content/Reliability/200_Labs/200_Deploy_and_Update_CloudFormation/5_add_ec2.md
> +{{< prev_next_button link_prev_url="../4_add_s3" link_next_url="../6_cleanup/" />}}
`6_cleanup` is not longer valid here

2021-03-31 23:37 UTC, setheliot approved these changes

2021-03-31 23:38 UTC, setheliot commented
changes were pulled in commit https://github.com/awslabs/aws-well-architected-labs/commit/a900bd0546346798019c40ad027741b0aea06470

2021-03-31 23:38 UTC, closed without merging