Add new reliability DR lab for analytics workload
awslabs/aws-well-architected-labs pull request #339
Opened 2021-08-22 16:04 UTC by rddefauw

*Issue #, if available:* n/a

*Description of changes:*

Adding a new 200-level reliability lab for an analytics workload.  The workload includes batch and stream processing components.  The lab shows how to do failover and "fail back" using the backup/restore pattern.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-28 00:29 UTC, setheliot requested changes
Hi Randy, this lab will make a great addition to the Well-Architected labs.
I left some comments. Let me know what you think.

In general, I think the lab would benefit from 
1. More explanation of what is happening an why
1. somewhat more "hand holding" on some of the steps

Thanks!

2021-08-28 00:29 UTC, setheliot commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +For RPO, you will lose whatever data your producers were trying to send to the endpoint from the time it became unhealthy to the time the failover completed.  You may also lose some data in the origi
Your DDB backup is hourly - does this play a role in the RPO (can lose up to an hours data).  Even if no, later in the lab you should explain how the DDB is backed up and how it is part of the strategy

2021-08-28 00:29 UTC, setheliot commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Architecture.md
> +## Disaster Recovery
Please explain more about your backup strategy.  Looks like you are using AWS Backup - can you show that and discuss that?

It is not clear to me how the DDB data gets into the recovery region.  Can you explain that?

2021-08-28 00:29 UTC, setheliot commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/Failover/_index.md
> +
add `{{% children /%}}` here

2021-08-28 00:29 UTC, setheliot commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/Failback/_index.md
> +
add `{{% children /%}}` here

2021-08-31 21:25 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +
Resolved in 2a371cc3

2021-08-31 21:37 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +
fixed in 4b5ec866

2021-08-31 22:32 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +In this module, you will go through the Backup and Restore DR strategy for an analytics workload. To learn more about this DR strategy, you can review this [Disaster Recovery blog](https://aws.amazon
fixed in f3deaf89

2021-08-31 23:23 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +In a nutshell, there are three primary data stores, S3, DynamoDB, and the Glue catalog.  The Glue catalog only receives new partitions as updates, and we use a Lambda function to create those when ne
fixed in 3eacc19c

2021-08-31 23:27 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +In a nutshell, there are three primary data stores, S3, DynamoDB, and the Glue catalog.  The Glue catalog only receives new partitions as updates, and we use a Lambda function to create those when ne
fixed in bb268800

2021-08-31 23:29 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/Failback/_index.md
> +
fixed in a21b9403

2021-08-31 23:30 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/Failover/_index.md
> +
fixed in 376f5026

2021-08-31 23:32 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/_index.md
> +
fixed in 3735f16b

2021-08-31 23:32 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/_index.md
> +
fixed in a9361ff5

2021-08-31 23:33 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +##### CLI Profiles
fixed in 5ff28361

2021-08-31 23:34 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +After you have your account identified, pick a primary AWS region to work in, such as `us-west-2`.  We'll refer to this as `REGION` going forward.  Then pick a backup region, such as `us-east-2`.  We
Got it.  It'll be much easier for them to use the default settings.  But I want to be sensitive to the folks in EMEA and APAC.

2021-08-31 23:39 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +You will have to create two prefix list in each region, one in the backup region and another one in the primary region.
Clarified that paragraph in 8ff05395

2021-08-31 23:42 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +First, create an S3 bucket to hold the CloudFormation templates.  We'll call this the `TEMPLATEBUCKET`.
fixed in 1793ccbe

2021-09-01 14:22 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +Note that we pass in the primary region as the fourth argument.
Explained this in bc9fbf63.  The argument refers to the region that the template bucket is in.

2021-09-01 15:05 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +weight: 10
We need to deploy a bucket into the backup region so we have a replication target for S3 CRR.  Added a note in 24f6e6ee.

2021-09-01 15:06 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/PrimaryRegion.md
> +In your working directory, place `create.sh` in a directory called `scripts` and place the file `workload.yaml` in a directory called `cfn`.  Place `tweetmaker.py` in a directory called `src` and `co
fixed in c21f2fd5

2021-09-01 15:12 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Architecture.md
> +Looking at our architecture, we have three primary data stores, S3, DynamoDB, and the Glue catalog.  For S3, we use cross-region replication to backup data to a DR region.  We use Lambda functions in
Added more explanation in 50567251.

2021-09-01 15:49 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +Review these files and adjust any of the input parameters to suit your needs.
Added a more detailed explanation in 5c1246a8.

2021-09-01 15:52 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +    ./scripts/create-dr.sh <template bucket> <template prefix> <stack name> <REGION> <backup bucket name> <inventory bucket name>
Added explanation and default values in 7d6268da.

2021-09-01 16:04 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/TestWorkload.md
> +Open a [Session Manager connection](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html) to the EC2 instance sample producer in the primary region.  You can find the ins
fixed in b275cbcc

2021-09-01 16:32 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +    ./scripts/create-dr.sh backuprestore cfn BackupRestore us-west-2 MyBackupBucket MyInventoryBucket
It's just for convenience, to avoid typing in such a lengthy command line.  Added a description.

2021-09-01 16:33 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/BackupRegion.md
> +### Deploy stack
Added a description of what this stack is deploying, and why we do it first.

2021-09-01 16:33 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/PrimaryRegion.md
> +    ./scripts/create.sh <template bucket> <template prefix> <stack name> <REGION> <backup bucket name> <ingress prefix list>
fixed in b6f11b4f

2021-09-01 16:43 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +Also note your AWS account number.  You find this in the console or by running `aws sts get-caller-identity` on the CLI.  We'll refer to this as `ACCOUNT` going forward.
Clarified the instructions in 2f502fd9.

2021-09-01 17:00 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +For instructions on creating prefix list, refer to the [documentation](https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html).
I added more notes in b9833e86.

2021-09-01 17:29 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Account.md
> +In this example `PRIMARY=us-west-2` and `BACKUP=us-east-2`.  Choose whichever regions you prefer.
We wanted to literally call them PRIMARY and BACKUP.  I clarified in f431d696

2021-09-01 17:30 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/SettingUp/TestWorkload.md
> +After a few minutes you should be able to preview the table in Athena and see some output.  The Glue database is called `backuprestoredb` and the raw tweets are in a table called `rawdata`.
Will do, adding more detail where noted.

2021-09-01 19:21 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/GettingStarted/Architecture.md
> +## Disaster Recovery
Clarified in ae3a7510.  We use DynamoDB PITR, and AWS Backup stores hourly copies.  During failover, we have a Lambda function that restore DynamoDB in the backup region from the most recent PITR snapshot.

2021-09-01 19:25 UTC, rddefauw commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/_index.en.md
> +For RPO, you will lose whatever data your producers were trying to send to the endpoint from the time it became unhealthy to the time the failover completed.  You may also lose some data in the origi
Actually we rely on PITR; Backup is used here for an extra layer of durability, but it's not what we rely on for DR.  I added a note on DynamoDB RPO in 87111f44.

2021-09-06 17:40 UTC, setheliot approved these changes
I will merge your commits, and then I will update the `{{% children /%}}` short codes

2021-09-06 17:40 UTC, setheliot commented on content/Reliability/200_Labs/200_Backup_Restore_Failback_Analytics/Failback/_index.md
> +
Hi Randy.  You must use `{{% children /%}}` (note the `/`) otherwise it prematuraly ends the page -- in this case the next/prev buttons are no longer shown

2021-09-06 17:40 UTC, merged