VPC Flow Logs QuickSight Analysis Dashboard Lab
awslabs/aws-well-architected-labs pull request #387
Opened 2021-11-03 19:54 UTC by chaitanyashah

*Description of changes:*

Created VPC Flow Logs QuickSight Analysis Dashboard Lab

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-03 20:56 UTC, setheliot requested changes
Hi, I did not complete my review, but I cannot finish it now.  Therefore I wanted you to have my comments do far

[head-up @benjipotter ]

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +Dashboard depends on all the fields below and required in VPC Flow Logs that are stored in S3:
I am not sure I understand this sentence, can you clarify?

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +This dashboard contains breakdowns with the following visuals. Available views are Summary, Details by daily, minutes level granularity and enhanced view:
Please be consistent with capitalization of view names.
Please add an oxford comma after "granularity"

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +- To allow customers to use VPC Flow Logs dashboard along with Data Transfer Dashboard to visualize and understand data transfer, IP traffic patterns. Pinpoint the problem areas or abillity to look i
Please either use grammatically correct sentences OR use bullet points.  This reads like bullet points, but is displayed in paragraph form

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +- An AWS Account
An [AWS Account](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html) that you are able to use for testing. This account MUST NOT be used for production or other purposes.

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +- Amazon [QuickSight](https://quicksight.aws.amazon.com/sn/start) user has been already created
should this instead link to https://docs.aws.amazon.com/quicksight/latest/user/provisioning-users.html ?

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +<!-- - AWS [CLI 2.0](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html) -->
delete this unused (commented out) content

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +**Additional Accounts:** These are other accoutns that you own and has VPCs that you wish to enable Flow Logs and have an ability to push it to Central AWS Account's S3 bucket.\
"accoutns"

Please spellcheck all contents

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +We assume that you already have VPC and existing resources running in your account. If you wish to crete VPC please refer to [documentation](https://docs.aws.amazon.com/directoryservice/latest/admin-
"crete"

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +We assume that you already have VPC and existing resources running in your account. If you wish to crete VPC please refer to [documentation](https://docs.aws.amazon.com/directoryservice/latest/admin-
"reseource"

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +We assume that you already have VPC and existing resources running in your account. If you wish to crete VPC please refer to [documentation](https://docs.aws.amazon.com/directoryservice/latest/admin-
Instead of sending them into the docs, please use our customer short codes to walk them through creating a  VPC.  You can put this inside a collapsible section so it is inly displayed to those who need it.

The short code is
```
{{% common/Create_VPC_Stack stackname="WebApp1-VPC" %}}
```

as used [here](https://github.com/awslabs/aws-well-architected-labs/blob/master/content/Reliability/100_Labs/100_Deploy_CloudFormation/1_deploy_vpc.md)  and you can see how it renders [here](https://wellarchitectedlabs.com/reliability/100_labs/100_deploy_cloudformation/1_deploy_vpc/)

Collapsible sections are also used on that same page

```
{{%expand "Click here for instructions how to deploy a VPC to your AWS account:" %}}
{{% common/Create_VPC_Stack stackname="WebApp1-VPC" %}}
{{% /expand%}}
```

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +We assume that you already have VPC and existing resources running in your account. If you wish to crete VPC please refer to [documentation](https://docs.aws.amazon.com/directoryservice/latest/admin-
additionally if you want to give them a "toy" app, they can use the one here https://wellarchitectedlabs.com/reliability/100_labs/100_deploy_cloudformation/2_deploy_webapp/

I am not sure if this will meet your needs for generating VPC flowlog traffic though

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +QuickSight dashboard provided in this lab requires all the fields mentioned in the [Introduction section](/security/300_labs/300_vpc_flow_logs_analysis_dashboard/#introduction) are required. If you a
please link to Create Athena resources, Lambda function and CloudWatch rule

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +{{% notice note %}}
**I am concerned that most students will not have have the existing infrastructure (and certainly not a multi-account infrastructure) to make use of this lab. I think you need to supply steps to create a "toy" application that will provide the data used in the dashboard. **

@benjipotter would like to hear what you think on this

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +2. Run CloudFormation stack to enable VPC Flow Logs.
OPTIONAL, but we already have a shortcode for deploying a CFN template -- usage notes are in the comments at the top

https://raw.githubusercontent.com/awslabs/aws-well-architected-labs/master/layouts/shortcodes/common/CreateNewCloudFormationStack.md

https://github.com/awslabs/aws-well-architected-labs/blob/master/layouts/shortcodes/common/CreateNewCloudFormationStack.md

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +2. Run CloudFormation stack to enable VPC Flow Logs.
Also deleting a stack https://github.com/awslabs/aws-well-architected-labs/blob/master/layouts/shortcodes/common/DeleteCloudFormationStack.md

2021-11-03 20:56 UTC, setheliot commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/1_enable_vpc_flow_logs.md
> +    - [vpc-flow-logs-custom.yaml](https://d36ux702kcm75i.cloudfront.net/vpc-flow-logs-custom.yaml)
please put all code used (including CloudFormation) in this repo.  The would go under `static`

2021-11-11 17:56 UTC, chaitanyashah commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +Dashboard depends on all the fields below and required in VPC Flow Logs that are stored in S3:
User can configure any fields they want to store in logrecord in s3 bucket (Default, Custom). VPC Flow Logs QuickSight dashboard needs customer to store all the available fields in logrecord to provide maximum value and show different dimensions in QS visuals. If any field is missing in S3 then QS dashboard will not work.

2021-11-11 21:19 UTC, chaitanyashah commented on content/Security/300_Labs/300_VPC_Flow_Logs_Analysis_Dashboard/_index.md
> +- Amazon [QuickSight](https://quicksight.aws.amazon.com/sn/start) user has been already created
Linked as suggested

2021-11-12 03:05 UTC, setheliot approved these changes

2021-11-12 03:25 UTC, merged

2021-11-12 03:27 UTC, setheliot commented
@chaitanyashah I merged your changes.  I made some small modifications. please see:
* https://github.com/awslabs/aws-well-architected-labs/commit/36406181a97b10c08c034576b11d39db843d37c4
* https://github.com/awslabs/aws-well-architected-labs/commit/101bf0762ae954bd6ae00315f5c0a781b40a5117