Budgets
awslabs/aws-well-architected-labs pull request #397
Opened 2021-11-12 14:04 UTC by awssteph

Added budgets collector module which can be used in CUDOS or CID dashabords

2021-11-15 16:37 UTC, awsdunc commented on content/Cost/300_Labs/300_Optimization_Data_Collection/3_Data_Collection_Modules.md
> +It is not partitioned. Currnetly this data looks for tags **'Env'** This can be updated in the lambda function **Environment Variables** separated by a comer.
Currnetly *minor typo*

2021-11-15 16:39 UTC, awsdunc commented on content/Cost/300_Labs/300_Optimization_Data_Collection/5_Utilize_Data.md
> +1. Ensure you have budget data in your athena table
Should athena be "Amazon Athena"?

2021-11-15 16:41 UTC, awsdunc requested changes
Few minor typos. Let me know if you would like me to run through the lab and check the steps/CF Template fully 👍

2021-11-15 21:46 UTC, yprikhodko commented on content/Cost/300_Labs/300_Optimization_Data_Collection/3_Data_Collection_Modules.md
> +                  TimeoutInMinutes: 5
Do we really need to have timeout set?

2021-11-15 21:46 UTC, yprikhodko commented on static/Cost/300_Optimization_Data_Collection/Code/Optimization_Data_Collector.yaml
> +      TimeoutInMinutes: 5
I think timeout can be dropped

2021-11-15 21:46 UTC, yprikhodko commented on static/Cost/300_Optimization_Data_Collection/Code/Budgets.yaml
> +            CREATE OR REPLACE VIEW aws_budgets_view AS
If this view is queried before default data delivery query to this view will fail as crawler hasn't been run yet. Probably worth to mention this in the lab to explain

2021-11-15 21:46 UTC, yprikhodko commented on static/Cost/300_Optimization_Data_Collection/Code/Budgets.yaml
> +    Description: Your Management Account ID
Should there be a policy adder to cfn which deployed in management account?

2021-11-17 11:13 UTC, awssteph commented on content/Cost/300_Labs/300_Optimization_Data_Collection/3_Data_Collection_Modules.md
> +It is not partitioned. Currnetly this data looks for tags **'Env'** This can be updated in the lambda function **Environment Variables** separated by a comer.
done

2021-11-17 11:13 UTC, awssteph commented on content/Cost/300_Labs/300_Optimization_Data_Collection/5_Utilize_Data.md
> +1. Ensure you have budget data in your athena table
done

2021-11-17 11:15 UTC, awssteph commented on content/Cost/300_Labs/300_Optimization_Data_Collection/3_Data_Collection_Modules.md
> +                  TimeoutInMinutes: 5
done

2021-11-17 11:15 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/Optimization_Data_Collector.yaml
> +      TimeoutInMinutes: 5
done

2021-11-17 11:16 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/Budgets.yaml
> +            CREATE OR REPLACE VIEW aws_budgets_view AS
done

2021-11-17 11:17 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/Budgets.yaml
> +    Description: Your Management Account ID
Its already done

2021-11-17 16:58 UTC, yprikhodko commented on static/Cost/300_Optimization_Data_Collection/Code/Budgets.yaml
> +                      for budget in budgets['Budgets']:
If customer doesn't have any budgets this will fail. Could you please add check for 'Budgets' key to handle it

2021-11-19 12:11 UTC, merged