WA Cost 100 Update
awslabs/aws-well-architected-labs pull request #573
Opened 2022-06-01 21:14 UTC by dbrickner

*Issue #, if available:*

*Description of changes:*
Level 100-AWS Account Setup-2. Create an account structure-Enable Service Control Policies
Update images for new console

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-08 16:53 UTC, iakov-aws requested changes

2022-06-08 16:53 UTC, iakov-aws commented on content/Cost/100_Labs/100_1_AWS_Account_Setup/4_configure_sso.md
> + - **Password** -
Typo?

2022-06-09 19:05 UTC, dbrickner commented on content/Cost/100_Labs/100_1_AWS_Account_Setup/4_configure_sso.md
> + - **Password** -
yes

2022-06-09 20:05 UTC, iakov-aws approved these changes

2022-06-09 20:05 UTC, merged