Doc improvements for CID
awslabs/aws-well-architected-labs pull request #592
Opened 2022-06-25 11:40 UTC by iakov-aws

*Issue #, if available:*

*Description of changes:*
Doc enhancements for CID

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-27 21:12 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +    + Ensure you select the region that is most appropriate based on where your S3 Bucket is located containing your Cost & Usage Report files.
Why CUR if it's CO prerequisites?

2022-06-27 21:15 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +### 4/4 Install Compute Optimizer Data Collection
What the benefit of moving this step to the last step?

2022-06-27 21:19 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> -{{%expand "Click here - to use AWS Cloudshell - Recommended option" %}}
Manual deployment still requires cli to be installed. I agree that this section shouldn't be here, but could you please move it manual deployment part of the dashboards?

2022-06-27 21:21 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Trusted Advisor Dashboards/Dashboards/1_prerequistes.md
> -**AWS CloudShell** is a browser-based, pre-authenticated shell that you can launch directly from the AWS Management Console. You can run AWS CLI commands against AWS services using your preferred she
Same comment as for CUR dashboards. Manual deployment still requires cli. Could you please move this to manual deployment part? We can't completely remove it

2022-06-27 21:27 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +        - If not configured, continue to setting up by clicking **Edit workgroup**
Looks like grammar typo. Maybe better 'continue set up by...'

2022-06-27 21:29 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +1. Click **Finish** & wait for the congratulations screen to display
which value brings this change?

2022-06-28 06:14 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +    + Ensure you select the region that is most appropriate based on where your S3 Bucket is located containing your Cost & Usage Report files.
Copy paste. Thanks good catch.

2022-06-28 06:16 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +### 4/4 Install Compute Optimizer Data Collection
You are right. 

The idea was that anyway we need athena for the lab. But u are right. Making a big step first makes more sence

2022-06-28 06:18 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +1. Click **Finish** & wait for the congratulations screen to display
align to other docs.

2022-06-28 06:20 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +    + Enable the Amazon S3 option and select the bucket where your **Cost & Usage Report** is stored, as well as your **Athena** query bucket. QuickSight will require write permissions for Athena que
fixed thanks

2022-06-28 06:21 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Trusted Advisor Dashboards/Dashboards/1_prerequistes.md
> -**AWS CloudShell** is a browser-based, pre-authenticated shell that you can launch directly from the AWS Management Console. You can run AWS CLI commands against AWS services using your preferred she
can we just give a reference to an official doc? 
 https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions

2022-06-28 06:28 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +        - If not configured, continue to setting up by clicking **Edit workgroup**
Fixed thanks

2022-06-28 06:29 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Trusted Advisor Dashboards/Dashboards/1_prerequistes.md
> -**AWS CloudShell** is a browser-based, pre-authenticated shell that you can launch directly from the AWS Management Console. You can run AWS CLI commands against AWS services using your preferred she
added to cur and tao. for CO i do not see a usecase for manual deployment

2022-06-28 06:29 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> -{{%expand "Click here - to use AWS Cloudshell - Recommended option" %}}
added reference to a public doc

2022-06-28 09:24 UTC, yprikhodko requested changes
@aaronedell could you please review this PR as well?

2022-06-28 09:33 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +1. Create a new S3 bucket for Athena queries to be logged to. Keep to the same region as the S3 bucket created for the data (ex: athena-query-result-REGION-ACCOUTID ).
To ease the copy paste in future. We have this pargraph in 3 places

2022-06-28 09:33 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +    + Ensure you select the region that is most appropriate based on where your S3 Bucket is located containing your Report files.
To ease the copy paste in future. We have this pargraph in 3 places

2022-06-28 09:35 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +1. Click **Finish** & wait for the congratulations screen to display
3 prereqs (CO, TAO and CUR)

2022-06-28 21:34 UTC, aaronedell commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> -{{%expand "Click here - to use AWS Cloudshell - Recommended option" %}}
While we prefer customers use Cloudshell, some have not been able to and like to use Terminal or some other command interface. This section is pretty long and complex, wondering if there is a simplification. Another problem with linking to public docs is that sometimes they go stale, or in general discourage customers a bit as its another place to go and complete a task.

2022-06-28 21:34 UTC, aaronedell commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/1_prerequistes.md
> +1. Click **Finish** & wait for the congratulations screen to display
We should avoid using abbreviations and symbols where possible to increase readability.

2022-06-28 21:35 UTC, aaronedell commented on content/Cost/200_Labs/200_Cloud_Intelligence/Compute Optimizer Dashboards/Dashboards/1_prerequisites.md
> +1. Create a new S3 bucket for Athena queries to be logged to. Keep to the same region as the S3 bucket created for the data (ex: athena-query-result-REGION-ACCOUTID ).
I'm torn with this one because although I agree consistency is good, being very clear which bucket we're talking about I think helps a lot.

2023-02-24 11:33 UTC, iakov-aws commented
Outdated. Closing

2023-02-24 11:33 UTC, closed without merging