Watool trusted advisor integration lab
awslabs/aws-well-architected-labs pull request #643
Opened 2022-08-16 11:35 UTC by awsdunc

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-25 03:08 UTC, sssalim-aws reviewed
Will it make more sense to prescribe the Tag  Key and Value ?

2022-08-25 03:10 UTC, sssalim-aws commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/1_prerequisites.md
> +Amazon EC2 Instances must have AWS Tags. If you have not associated AWS Tags with Amazon EC2 Instances with any AWS Tags, [tag your Amazon EC2 resources](https://docs.aws.amazon.com/AWSEC2/latest/Use
Will it make more sense to prescribe the tag ?

 ```
    Key = workload
    Value = wademo
    ```

2022-08-25 03:33 UTC, sssalim-aws requested changes
Please see comment on Pre-req. and fix image /Images/section5/workloadID.png to use image block rather than pen scratch.

2022-08-25 03:33 UTC, sssalim-aws commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/1_prerequisites.md
> +Amazon EC2 Instances must have AWS Tags. If you have not associated AWS Tags with Amazon EC2 Instances with any AWS Tags, [tag your Amazon EC2 resources](https://docs.aws.amazon.com/AWSEC2/latest/Use
Will it make more sense to prescribe the tag ?

 ```
    Key = workload
    Value = wademo
    ```

2022-08-25 13:08 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/1_prerequisites.md
> +Amazon EC2 Instances must have AWS Tags. If you have not associated AWS Tags with Amazon EC2 Instances with any AWS Tags, [tag your Amazon EC2 resources](https://docs.aws.amazon.com/AWSEC2/latest/Use
updated as follows:
 Key = Environment
 Value = watooldemo

2022-08-25 13:08 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +1. Amazon API Gateway has been provided and IAM role to invoke AWS Lambda function with mapping table that contains AWS Trusted Advisor Check IDs and Question ID of questions in Well-Architected Tool
updated

2022-08-25 13:09 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +3. In Well-Architected Tool, a reviewer will define a workload which is a collection of resources and applications that delivers business value.
updated

2022-08-25 13:09 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +4. Defining a workload in Well-Architected Tool generates an event called **CreateWorkload** that Amazon EventBridge receives, which will invoke another AWS Lambda function.
updated

2022-08-25 13:09 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +5. This AWS Lambda function collects finding, reason, and recommended instance type for the rightsizing from **AWS Compute Optimizer**. It also gathers the details of "**Low Utilization Amazon EC2 In
updated

2022-08-25 13:17 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/_index.md
> +AWS Well-Architected Framework Review is a constructive conversation about architectural decisions. One of the best ways to maximize the impact of the review is to be equipped with the preliminary re
updated

2022-08-25 13:17 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/_index.md
> +AWS Well-Architected Framework Review is a constructive conversation about architectural decisions. One of the best ways to maximize the impact of the review is to be equipped with the preliminary re
updated

2022-08-25 13:17 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +4. Now we will update the AWS DynamoDB table with a sample mapping table in json file through API Gateway. This mapping table has Question ID of Well-Architected question associated with AWS Trusted
updated

2022-08-25 13:17 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +7. There are 1 Question IDs of Well-Architected questions and 1 AWS Trusted Advisor checks.
updated

2022-08-25 13:17 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/3_create_workload.md
> +Well-Architected Framework Reviews are conducted per workload. A workload is a collection of resources and code that delivers business value, such as a customer-facing application or a backend proces
updated

2022-08-25 13:21 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/3_create_workload.md
> +4. Choose the lenses that apply to this workload. **AWS Well-Architected Framework** has been selected by default.
updated

2022-08-25 13:21 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/4_perform_review.md
> +![Section4 Integration](/watool/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/Images/section4/TA_Aco_integration.png)
updated

2022-08-25 13:24 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/1_prerequisites.md
> +Amazon EC2 Instances must have AWS Tags. If you have not associated AWS Tags with Amazon EC2 Instances with any AWS Tags, [tag your Amazon EC2 resources](https://docs.aws.amazon.com/AWSEC2/latest/Use
took a new screenshot and replaced

2022-08-26 03:20 UTC, awswa commented
> 

I made changes that reviewers addressed

2022-08-26 03:21 UTC, awswa approved these changes
I made changes that reviewers addressed

2022-08-26 03:47 UTC, awswa reviewed
I have made changes based on comments from reviewers.

2022-08-26 03:47 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/1_prerequisites.md
> +Amazon EC2 Instances must have AWS Tags. If you have not associated AWS Tags with Amazon EC2 Instances with any AWS Tags, [tag your Amazon EC2 resources](https://docs.aws.amazon.com/AWSEC2/latest/Use
> Will it make more sense to prescribe the tag ?
> 
> ```
>    Key = workload
>    Value = wademo
>    ```
> ```

took a new screenshot and replaced

2022-08-26 03:47 UTC, awswa commented on content/Well-ArchitectedTool/200_Labs/200_Integration_with_AWS_Compute_Optimizer_and_AWS_Trusted_Advisor/2_configure_env.md
> +1. Amazon API Gateway has been provided and IAM role to invoke AWS Lambda function with mapping table that contains AWS Trusted Advisor Check IDs and Question ID of questions in Well-Architected Tool
> Our SAM deployment includes an Amazon API gateway with an IAM role to invoke our Lambda function. This function references a JSON mapping file that contains trusted advisor check IDs allowing for mapping to the appropriate questions within the Well-Architected tool.

update!

2022-08-26 03:52 UTC, awswa approved these changes
I have completed all changes and it's ready to be published.

2022-08-26 04:17 UTC, sssalim-aws approved these changes
Review Completed by sssalim & tearatim, approving change.

2022-08-26 04:17 UTC, merged