Sustainability hardware pattern optimisation Lab
awslabs/aws-well-architected-labs pull request #644
Opened 2022-08-16 11:41 UTC by awsdunc

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-26 15:55 UTC, thomasattree requested changes
Please see specific line comments for detail.

Overall the lab seems to flow, I've made some minor wording changes and pushed these to your PR.
Make sure to include summaries across all of the pages to re-inforce learnings the participant makes.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +    businessapi.php
This mismatches line 51

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +    2. **Click radio slider** as you will select the existing metric namespace.
Might need a small screenshot for this

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +
You may want to add here that it may take a few minutes for metrics to be displayed on the graph.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +
Add a summary at the bottom of this lab step to summarize what the participant just did and what they should have learned from it.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +![Section3 formula](/Sustainability/200_optimize_ec2_using_cloudwatch_compute_optimizer/Images/section3/formula.png)
Whilst this is a good graphic, consider also typing the formula out as the PNG would not be accessible for those using screen readers.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +**Note** - It may take up to 12 hours for AWS Compute Optimizer to fully analyze the AWS resources in your account, which will incur costs in your account. You may refer to the following screenshots
Make sure this is called out in the lab index page under lab duration. It's 40 minutes + 12 hours if you want to complete the compute optimizer parts yourself. And in in the prerequisites. Clarify the costings.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +**Note** - Remind you of "**Anticipate and adopt new, more efficient hardware and software offerings**" design principle in Sustainability pillar. AWS Graviton3 processors instance use up to **60 per
Need to ensure this is updated when compute optimizer includes graviton 3 based instance types.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +{{%expand "Click here for CloudFormation console deployment steps"%}}
We're not just deploying cloudformation in this step, but also have connecting to EC2 and generating load steps. The expand should be used if instructions are optional and provide guidance for less experienced users, but it seems the additional steps shouldn't be within the expand section.

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +7. Now you successfully replaced **t4g.xlarge** with **c6g.xlarge**. Let's generate the same workloads to compare sustainability KPI we previously created using CloudWatch metrics with metric math fu
Why do we have to do this? Didn't have to do it for the previous instance type. Could they be made to be consistent for the user?

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +
Add a summary here of what the participant achieved in this section

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/cleanup.md
> +
Cleanup steps appear to be incomplete for the cloudwatch dashboard?

2022-08-26 15:55 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +{{%expand "Click here for CloudFormation console deployment steps"%}}
After reviewing the cloudformation template for the c6g instance, I don't believe the user needs to connect to the instance and generate load. Consider removing these steps?

2022-08-27 07:06 UTC, awswa reviewed
I have reviewed each comments from Thomas and updated the instructions.

2022-08-27 07:06 UTC, awswa commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/cleanup.md
> +
> Cleanup steps appear to be incomplete for the cloudwatch dashboard?

you are right. I have updated the steps accordingly.

2022-08-29 12:26 UTC, teratim requested changes

2022-08-29 12:28 UTC, teratim commented
done

2022-08-30 02:47 UTC, awswa reviewed
I have updated instructions based on reviewer's comments.

2022-08-30 03:10 UTC, awswa reviewed
test comment and disregard this

2022-08-30 03:10 UTC, awswa commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/3_baseline_sustainability_kpi.md
> +
test

2022-08-30 04:21 UTC, teratim commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +7. Now you successfully replaced **t4g.xlarge** with **c6g.xlarge**. The same workloads will be automatically generated to evaluate sustainability KPIs we previously created. Tick a box to **select S
You have now actioned the recommended changes from AWS Compute Optimizer, replacing your existing t4g.xlarge instance with c6g.large. The previous sustainability KPIs which we calculated will now have been automatically updated.

2022-08-30 04:21 UTC, teratim commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/5_review_sustainability_kpi_optimization.md
> +With optimization completed in the previous lab, let’s evaluate if you maximized utilization and improved our sustainability KPIs:
With our EC2 instance optimization completed, let’s evaluate our utilization levels to see if they have improved and effected our sustainability KPIs.

2022-08-30 04:21 UTC, teratim commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/5_review_sustainability_kpi_optimization.md
> +1. With c6g.large instance, CPU utilization appears to be 26% from 13%, which means we maximized compute resources. You reduced idle resources and met performance requirements.
With our new c6g.large instance, CPU utilization appears to be running at ~26% compared to the previous utilization levels of ~13%. This has dramatically reduced the amount of our idle resources and allowed us to still meet our performance requirements.

2022-08-30 04:21 UTC, teratim commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/5_review_sustainability_kpi_optimization.md
> +With, that below are improved metrics and KPIs:
These are the improved metrics and KPIs:

2022-08-30 08:48 UTC, thomasattree commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +
For your summaries, add a lower level heading like

### Summary

The summary you've given here is a bit too literal, refresh the reader on why they've done those steps.

"In this section, you successfully replaced t4g.xlarge with c6g.large using the second AWS CloudFormation template of the lab. You generated API calls in a replaced Amazon EC2 instance. We will use these newer metrics next to review the improvements against our sustainability KPI"

2022-08-30 09:43 UTC, awswa reviewed
updated the instructions based on reviewers' comments

2022-08-30 09:43 UTC, awswa commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/5_review_sustainability_kpi_optimization.md
> +1. With c6g.large instance, CPU utilization appears to be 26% from 13%, which means we maximized compute resources. You reduced idle resources and met performance requirements.
> With our new c6g.large instance, CPU utilization appears to be running at ~26% compared to the previous utilization levels of ~13%. This has dramatically reduced the amount of our idle resources and allowed us to still meet our performance requirements.

move this to step 4 from step 5

2022-08-30 09:43 UTC, awswa commented on content/Sustainability/200_Labs/200_optimize_ec2_using_cloudwatch_compute_optimizer/4_reducing_idle_resources_and_maximizing_utilization.md
> +
> In this section, you successfully replaced t4g.xlarge with c6g.large using the second AWS CloudFormation template of the lab. You generated API calls in a replaced Amazon EC2 instance. We will use these newer metrics next to review the improvements against our sustainability KPI

updated as Thomas recommended

2022-09-01 01:10 UTC, sssalim-aws approved these changes
Spoke to @awswa , Peer Review has been completed. Approving this on behalf of @teratim

2022-09-01 01:11 UTC, sssalim-aws approved these changes
Spoke to @awswa , Peer Review has been completed. Approving this on behalf of @thomasattree

2022-09-01 01:13 UTC, sssalim-aws approved these changes
Spoke to Jang, Peer Review has been completed. Approving this on behalf of @teratim

2022-09-01 01:17 UTC, sssalim-aws approved these changes
Approving Changes

2022-09-01 01:18 UTC, sssalim-aws approved these changes

2022-09-01 01:20 UTC, sssalim-aws approved these changes

2022-09-01 04:20 UTC, teratim approved these changes

2022-09-01 12:03 UTC, merged