ADDED Multi Account Setup section in 200 Cloud Intelligence - Cost & Usage Report Dashboards
awslabs/aws-well-architected-labs pull request #655
Opened 2022-08-25 11:14 UTC by tbuatois

This PR add a new section in the 200 Labs, Cloud Intelligence, Cost & Usage Report Dashboards. 

The new section adds: Multiple Account CUR Aggregation setup for multiple linked account and payer account. The referenced in the FAQ to Multi Payer account setup has been move to this new section. 

A CloudFormation template in `static/Cost/200_Cloud_Intelligence/templates/cur-aggregation/cur-aggregation.yaml` needs to be upload to s3 and made available publicly.

2022-08-25 11:37 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/FAQ/_index.md
> -
Can we keep the header and add url to the new doc? 
We have this FAQ url in many places

2022-08-25 13:07 UTC, tbuatois commented on content/Cost/200_Labs/200_Cloud_Intelligence/FAQ/_index.md
> -
Great idea, I've re added the FAQ section with a link to the new multi-account setup page

2022-08-27 08:16 UTC, iakov-aws approved these changes

2022-08-27 08:16 UTC, iakov-aws commented
Approved. Wating for 2nd approval from @yprikhodko

2022-08-28 22:28 UTC, yprikhodko requested changes
Appreciate your work on this. I've left plenty of comments, please address them and if needed we can discuss over the call, but please don't merge as is. General thoughts:
1. I don't think it should be step 4 of this lab as customers get there after 1,2,3. It should be either prerequisites or separate module outside of CID, or FAQ as it is now describing multi-account CUR set-up 
2. It should focus only on multi-account set up, please don't add any dashboards deployment steps, but reference existing ones

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +### Option 2: (Recomended) From Payer Account(s) to a Dedicated CUR Aggregation Account
Add architecture diagram here the same as in manual deployment

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/FAQ/_index.md
>  ## How do I setup the dashboards on top of multiple payer accounts?
I recommend to leave multi-payer deployment here as it used to be. another option make it part of prerequisites, but it might make prerequisites heavy.

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +## Deploy Dashboards via CLI
This shouldn't be here. Multi-payer set up should cover only multi-payer set up and reference existing deployment pages as link

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +### Saving and Sharing your Dashboard in QuickSight
The same comment, this shouldn't be here as we talk about multi-payer set up

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +## Advanced
I suggest to re-phrase to 'Advanced steps'

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +4. Enter a **Stack name** for your template such as **CID-DedicatedDataCollectionAccount**.
CUR replication is generic step, which might be used by customers out of scope of the dashboards. Which value CID adds in the names here?

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +![Images/multi-account/cfn_dash_param_2.png](/Cost/200_Cloud_Intelligence/Images/multi-account/cfn_dash_param_2.png?classes=lab_picture_small)
Please re-phrase descriptions of parameters, multi-account cur set up is generic steps and I don't see a value mentioning CID or QuickSight in the parameter names or descriptions. Customers might want to use this lab for general CUR replication. That's why I believe it could have a better place  then step 4 of this lab.

2022-08-28 22:28 UTC, yprikhodko commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +### Deploy CUR Replication on Other Accounts
On Payer accounts?

2022-08-29 05:35 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +#### 2. Deployment of the Dashboards
@yprikhodko There are specific requirements when installing dashboard after executing this.

2022-08-29 05:37 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +4. Enter a **Stack name** for your template such as **CID-DedicatedDataCollectionAccount**.
We prefix all assets as CID (cloud intelligence dashboard) to help user identify them.

2022-08-29 05:38 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +![Images/multi-account/cfn_dash_param_2.png](/Cost/200_Cloud_Intelligence/Images/multi-account/cfn_dash_param_2.png?classes=lab_picture_small)
Same 

We prefix all assets as CID (cloud intelligence dashboard) to help user identify them.

2022-08-29 05:49 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +## Prerequisites
How exactly you see this? 
ex: 
1. remove from [prereqs](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/
) mention of CUR
2. Rename prereqs to 1b_prerequistes/
3. Add 1a_cur_setup with Single and multi account setups both automated and manual? 
@yprikhodko  can you confirm?

2022-08-29 05:57 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/FAQ/_index.md
>  ## How do I setup the dashboards on top of multiple payer accounts?
We may want to extend this FAQ further with FAQ content. CUR setup deserves a dedicated page.  I would go for a splitted prereqs page to make it less heavy. This way we can share the direct url for multi account setup at the moment the customer transition from single to multi payer (quite frequent usecase from what i see)

2022-08-29 05:58 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +title: "Multi-Account Setup"
How exactly you see this?
ex:

    remove from [prereqs](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/) mention of CUR
    Rename prereqs to 1b_prerequistes/
    Add 1a_cur_setup with Single and multi account setups both automated and manual?
    @yprikhodko can you confirm?

2022-08-29 06:03 UTC, iakov-aws commented on content/Cost/200_Labs/200_Cloud_Intelligence/Cost & Usage Report Dashboards/Dashboards/4_multi_account_setup.md
> +## Deploy Dashboards via CLI
Plese note that there are specific parameters we need to use in CID: 

```bash
cid-cmd deploy \
  --athena-database centralized-cur-db \
  --athena-workgroup centralized-cur-wk
```

One solution would be to default them in cid-cmd  (or align on a naming ex: athena-database: `cid` athena-workgroup: `cid` )

@yprikhodko what do you think?

2022-09-02 18:49 UTC, iakov-aws commented on static/Cost/200_Cloud_Intelligence/templates/cur-aggregation/cur-aggregation.yaml
> +            Fn::Sub: 's3://${S3}/athena-query-results/'
buckets with athena-query-results can grow over time. it might be useful to use another bucket with a lifecycle policy to delete all files older than 1-2 (?) days.

2023-02-24 12:13 UTC, iakov-aws commented
Processed long time ago in another PR. Thanks!

2023-02-24 12:13 UTC, closed without merging