Updated to accommodate UI changes in creating stacks and replicating …
awslabs/aws-well-architected-labs pull request #672
Opened 2022-09-06 23:50 UTC by RodneyLester

*Issue #671:*

*Description of changes:*

I updated the first step, deploy infrastructure, to make it clearer to click "Next" until you are prompted to okay creation of IAM resources.
I updated the second step, configure replication, to have screenshots of the current UI and to use the current text of that UI.

I updated 4 screenshots in the second step.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-09 16:38 UTC, RodneyLester commented
Pushing for my mentee to use and closing issues #671 and #615

2022-09-12 22:16 UTC, setheliot requested changes
- images should be 1200px wide maximum.. please resize static/Reliability/200_Bidirectional_Replication_for_S3/Images/ReplicatedObject.png
- see other comments about KMS

2022-09-12 22:16 UTC, setheliot commented on content/Reliability/200_Labs/200_Bidirectional_Replication_for_S3/2_configure_replication.md
> +1. For **Encryption**, select **Replicate objects encrypted with AWS KMS** and leave **AWS managed key (aws/s3)** selected.
Why are you changing this setting?  Used to be leave **Replicate objects encrypted with AWS KMS** _not_ selected -- see old lines 28-32

2022-09-12 22:16 UTC, setheliot commented on content/Reliability/200_Labs/200_Bidirectional_Replication_for_S3/2_configure_replication.md
> +1. For **Encryption**, select **Replicate objects encrypted with AWS KMS** and leave **AWS managed key (aws/s3)** selected.
Why are you changing this setting? Used to be leave Replicate objects encrypted with AWS KMS not selected -- see old lines 92-96

2022-09-12 23:06 UTC, RodneyLester commented on content/Reliability/200_Labs/200_Bidirectional_Replication_for_S3/2_configure_replication.md
> +1. For **Encryption**, select **Replicate objects encrypted with AWS KMS** and leave **AWS managed key (aws/s3)** selected.
It doesn't work if you do that. Verified that with my mentee. I'll scale the images down.

2022-09-13 00:04 UTC, RodneyLester commented on content/Reliability/200_Labs/200_Bidirectional_Replication_for_S3/2_configure_replication.md
> +1. For **Encryption**, select **Replicate objects encrypted with AWS KMS** and leave **AWS managed key (aws/s3)** selected.
Scaled down - take a look

2022-09-13 00:34 UTC, setheliot approved these changes

2022-09-13 00:34 UTC, merged