Twg
awslabs/aws-well-architected-labs pull request #693
Opened 2022-09-29 18:03 UTC by zxianshu

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-03 14:52 UTC, iakov-aws requested changes

2022-10-04 07:21 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/source/tg.py
> +    print(event)
thank you

2022-10-04 07:21 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/source/tg.py
> +lambda_handler(None, None)
thanks

2022-10-04 07:21 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/source/tg.py
> +                        f"{os.environ['TABLE']}/year={year}/month={month}/tgw-{item['TransitGatewayAttachmentId']}-{region_name}.json")
will be but not sure which PR is in first as multi payer is not merged

2022-10-04 07:26 UTC, zxianshu commented
Thanks @iakov-aws I've deleted that file. It is a test file and we forgot to delete it.

2022-10-04 17:45 UTC, yprikhodko commented on static/Cost/300_Optimization_Data_Collection/Code/transit_gateway.yaml
> +    Default: "cron(30 12 1 * ? *)"
seems like a wrong default value for GlueRoleARN param

2022-10-05 10:12 UTC, zxianshu commented on static/Cost/300_Optimization_Data_Collection/Code/transit_gateway.yaml
> +  CURTable:
upgraded to be the same as other modules

2022-10-05 10:13 UTC, zxianshu commented on static/Cost/300_Optimization_Data_Collection/Code/transit_gateway.yaml
> +    Default: "cron(30 12 1 * ? *)"
updated

2022-10-05 10:22 UTC, zxianshu commented on static/Cost/300_Optimization_Data_Collection/Code/transit_gateway.yaml
> +    Default: "cron(30 12 1 * ? *)"
@yprikhodko updated

2022-10-05 10:22 UTC, zxianshu commented on static/Cost/300_Optimization_Data_Collection/Code/transit_gateway.yaml
> +  CURTable:
@yprikhodko

2022-10-07 07:24 UTC, yprikhodko approved these changes

2022-10-07 09:15 UTC, awssteph approved these changes

2022-10-07 09:15 UTC, awssteph commented on static/Cost/300_Optimization_Data_Collection/Code/Optimization_Data_Collector.yaml
> +      TemplateURL: "https://aws-well-architected-labs.s3-us-west-2.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/transit_gateway_dev.yaml"
remove Dev and we wil be ready to go

2022-10-07 09:23 UTC, merged