Pull request for new lab - 200 - BUILD AWS HEALTH AWARE OPERATION CHANGE PROCESS Authors
awslabs/aws-well-architected-labs pull request #794
Opened 2023-01-04 04:00 UTC by JerryChenZeyun

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-04 04:01 UTC, JerryChenZeyun commented
It's been reviewed and approved by Rich Boyd (ricboy@) and Phong Le (huu@).

2023-01-04 04:01 UTC, JerryChenZeyun commented
It's been reviewed and approved by Rich Boyd (ricboy@) and Phong Le (huu@).

2023-01-05 08:51 UTC, sssalim-aws approved these changes
Approving new Lab.
Lab has been reviewed by Ops Pillar Lead

2023-01-05 08:52 UTC, sssalim-aws approved these changes

2023-01-05 08:53 UTC, sssalim-aws approved these changes

2023-01-05 08:56 UTC, sssalim-aws approved these changes

2023-01-05 08:56 UTC, sssalim-aws approved these changes
Approving

2023-01-16 03:57 UTC, JerryChenZeyun reviewed
submitted again.

2023-01-20 10:48 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +**Sign in to the [AWS Management Console](https://us-east-1.console.aws.amazon.com/console) as an IAM user who has the following permissions to ensure successful execution of this lab:**
Should we be advising to use IAM users? Or pushing for them to use a federated role? Can we rephrase this?

2023-01-20 10:49 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +2. scroll down to click the **checkbox** to acknowledge that the CloudFormation template might create IAM resources with custom names, and then click the **Create stack** button to proceed the stack
Capital S in Scroll

2023-01-20 10:54 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +
Too many spaces

2023-01-20 10:56 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +You can click [this link](https://us-east-1.console.aws.amazon.com/systems-manager/inventory?region=us-east-1) to go to Systems Manager Inventory in the console service. Or you may click the **Invent
Remove "You can"

2023-01-20 10:58 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +When you created the CloudFormation stack in the previous step, it's provisioned a SNS Topic **ssms-change-process-interruption-notification-sns-topic** to be used in this lab. To be able to receive
"you" need to subscribe to the SNS Topic

2023-01-20 11:01 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +**Step 2:** In the Topic detail page, click the **Create subscription** button.
SNS Topic

2023-01-20 11:04 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/2_create_ssm_change_template.md
> +
too many spaces?

2023-01-20 11:11 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/2_create_ssm_change_template.md
> +
Can we use switch role to avoid creating a second user here?

2023-01-20 11:11 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Create a first change request through Change Manager (in the current section) to test the AWS Health Aware capability of your Change Process. In most cases there's no active AWS service events when
opeartion -> operation

2023-01-20 11:12 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Step 1. Poll [AWS Health API](https://docs.aws.amazon.com/health/latest/ug/health-api.html) - The script in this step will call AWS Health [DescribeEvents API](https://docs.aws.amazon.com/health/la
"The function will then complete the event..."

2023-01-20 11:15 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Step 2. If there's active AWS Service events, then suspend the workflow, and send SNS notification to admins.
This sounds like the user has to do this manually, this is all automatic?

2023-01-20 11:16 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +1. **Sign in to the [AWS Management Console](https://us-east-1.console.aws.amazon.com/console) with the previous IAM user who has the following permissions to ensure successful execution of this lab:
See switch role comment further up

2023-01-20 11:18 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +7. Leave all parameter in the **Specify parameters** page as default, and click the **Next** button.
parameters plural?

2023-01-20 11:19 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +8. Review the configuration information in the **Review and submit** page, scroll down to the bottom of the page and click the **Submit for approval** button. Then the request has been successfully s
The request has been successfully submitted when a green banner shows at the top of the page.

2023-01-20 11:23 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +7. Leave all parameter in the **Specify parameters** page as default, and click the **Next** button.
parameters plural?

2023-01-20 11:23 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +#### Congratulations !
Is this consistent with the other pages end section?

2023-01-20 11:24 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +12. You will also receive email notification with the impacted service information.
You will also receive an email notification*

2023-01-20 11:25 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +13. Click [this link](https://health.aws.amazon.com/health/home#/account/event-log) to view the **AWS Health Event log**. Please note that we simulated the AWS service events using the historical eve
missing space between case.You

2023-01-20 11:27 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/_index.md
> +However there's an opportunity to use [AWS Health API](https://docs.aws.amazon.com/health/latest/ug/health-api.html) to build an AWS health aware operation change process with [AWS Systems Manager](h
derisks?

2023-01-20 11:28 UTC, awsdunc commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/_index.md
> +* An [IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users.html) in your AWS account with full access to [CloudFormation](https://aws.amazon.com/cloudformation/), [Amazon EC2](https://
Maybe call out that having an assumed role for this is a better pattern

2023-01-20 11:28 UTC, awsdunc requested changes
See comments inline

2023-01-31 03:45 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +**Sign in to the [AWS Management Console](https://us-east-1.console.aws.amazon.com/console) as an IAM user who has the following permissions to ensure successful execution of this lab:**
Have updated the lab (both page content and code) to replace the IAM user with a IAM role. So now there's NO IAM user being created by the lab.

2023-01-31 03:45 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/2_create_ssm_change_template.md
> +
Have updated the lab (both page content and code) to replace the IAM user with a IAM role. So now there's NO IAM user being created by the lab.

2023-01-31 09:55 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +2. scroll down to click the **checkbox** to acknowledge that the CloudFormation template might create IAM resources with custom names, and then click the **Create stack** button to proceed the stack
Changed.

2023-01-31 09:56 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +
Changed.

2023-01-31 09:57 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +You can click [this link](https://us-east-1.console.aws.amazon.com/systems-manager/inventory?region=us-east-1) to go to Systems Manager Inventory in the console service. Or you may click the **Invent
Removed.

2023-01-31 09:58 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +When you created the CloudFormation stack in the previous step, it's provisioned a SNS Topic **ssms-change-process-interruption-notification-sns-topic** to be used in this lab. To be able to receive
Changed.

2023-01-31 09:59 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/1_deploy_ssm_application_environment.md
> +**Step 2:** In the Topic detail page, click the **Create subscription** button.
Changed.

2023-01-31 10:02 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/2_create_ssm_change_template.md
> +
Changed.

2023-01-31 10:03 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Create a first change request through Change Manager (in the current section) to test the AWS Health Aware capability of your Change Process. In most cases there's no active AWS service events when
Changed.

2023-01-31 10:04 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Step 1. Poll [AWS Health API](https://docs.aws.amazon.com/health/latest/ug/health-api.html) - The script in this step will call AWS Health [DescribeEvents API](https://docs.aws.amazon.com/health/la
Changed.

2023-01-31 10:10 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +* Step 2. If there's active AWS Service events, then suspend the workflow, and send SNS notification to admins.
Changed the wording: "2. The AWS Systems Manager will automatically execute the runbook with dynamic automation..."

2023-01-31 10:12 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +7. Leave all parameter in the **Specify parameters** page as default, and click the **Next** button.
Yes - https://www.wordhippo.com/what-is/the-plural-of/parameter.html

2023-01-31 10:13 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +1. **Sign in to the [AWS Management Console](https://us-east-1.console.aws.amazon.com/console) with the previous IAM user who has the following permissions to ensure successful execution of this lab:
Updated - now using IAM role instead of IAM user to approve the template.

2023-01-31 10:16 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/3_test_change_process.md
> +8. Review the configuration information in the **Review and submit** page, scroll down to the bottom of the page and click the **Submit for approval** button. Then the request has been successfully s
Changed.

2023-01-31 10:17 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +7. Leave all parameter in the **Specify parameters** page as default, and click the **Next** button.
Yes - https://www.wordhippo.com/what-is/the-plural-of/parameter.html

2023-01-31 10:21 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/4_test_change_process_with_simulated_service_event.md
> +13. Click [this link](https://health.aws.amazon.com/health/home#/account/event-log) to view the **AWS Health Event log**. Please note that we simulated the AWS service events using the historical eve
Changed.

2023-01-31 10:22 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/5_cleanup.md
> +### Cleaning up the Systems Manager Resources
Changed - now using IAM role rather than IAM user as mentioned above.

2023-01-31 10:24 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/_index.md
> +However there's an opportunity to use [AWS Health API](https://docs.aws.amazon.com/health/latest/ug/health-api.html) to build an AWS health aware operation change process with [AWS Systems Manager](h
Changed - "... which avoids the change process being impacted ..."

2023-01-31 10:25 UTC, JerryChenZeyun commented on content/Operational Excellence/200_Labs/200_Build_AWS_Health_Aware_Operation_Change_Process/_index.md
> +* An [IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users.html) in your AWS account with full access to [CloudFormation](https://aws.amazon.com/cloudformation/), [Amazon EC2](https://
Changed - now using IAM role rather than IAM user.

2023-02-01 09:52 UTC, awsdunc approved these changes
LGTM

2023-02-01 09:52 UTC, merged